// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/viewmodels/pets_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i7;

import 'package:petsos/models/data/repositories/pets_repository.dart' as _i2;
import 'package:petsos/models/pet.dart' as _i4;
import 'package:petsos/models/data/services/storage_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PetsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPetsRepository extends _i1.Mock implements _i2.PetsRepository {
  @override
  _i3.Stream<List<_i4.Pet>> getPetsStream() => (super.noSuchMethod(
        Invocation.method(
          #getPetsStream,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.Pet>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i4.Pet>>.empty(),
      ) as _i3.Stream<List<_i4.Pet>>);

  @override
  _i3.Future<List<_i4.Pet>> getPets() => (super.noSuchMethod(
        Invocation.method(
          #getPets,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Pet>>.value(<_i4.Pet>[]),
        returnValueForMissingStub: _i3.Future<List<_i4.Pet>>.value(<_i4.Pet>[]),
      ) as _i3.Future<List<_i4.Pet>>);

  @override
  _i3.Future<_i4.Pet?> getPetById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getPetById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Pet?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.Pet?>.value(),
      ) as _i3.Future<_i4.Pet?>);

  @override
  _i3.Future<String> addPet(_i4.Pet? pet) => (super.noSuchMethod(
        Invocation.method(
          #addPet,
          [pet],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #addPet,
            [pet],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #addPet,
            [pet],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> updatePet(
    String? id,
    _i4.Pet? pet,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePet,
          [
            id,
            pet,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deletePet(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePet,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Pet>> searchPetsByBreed(String? breed) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPetsByBreed,
          [breed],
        ),
        returnValue: _i3.Future<List<_i4.Pet>>.value(<_i4.Pet>[]),
        returnValueForMissingStub: _i3.Future<List<_i4.Pet>>.value(<_i4.Pet>[]),
      ) as _i3.Future<List<_i4.Pet>>);

  @override
  _i3.Stream<List<_i4.Pet>> getPetsByLocation(
    double? lat,
    double? lng,
    double? radiusKm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPetsByLocation,
          [
            lat,
            lng,
            radiusKm,
          ],
        ),
        returnValue: _i3.Stream<List<_i4.Pet>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i4.Pet>>.empty(),
      ) as _i3.Stream<List<_i4.Pet>>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i6.StorageService {
  @override
  _i3.Future<String?> uploadImage(
    _i7.File? file, {
    String? folder = 'pets',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [file],
          {#folder: folder},
        ),
        returnValue: _i3.Future<String?>.value(),
        returnValueForMissingStub: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
}
